### ISSUE TITLE
No default page is created after alchemy:db:seed

### ISSUE THREAD

**Issue by moritzps** [AlchemyCMS/alchemy-demo#1]
After cloning the repo I ran _bundle install_ and after that _rake db:create db:migrate alchemy:db:seed_. 

A default language tree was created but **no index page was created**. I dropped my database and tried again but had no luck: I was not able to create a page in the language tree. Creating another language tree again resulted in an empty tree where I can not add pages.

**Comment by agorneo** [comment]
I have a very similar issue...
Procedure: 
-) clone demo
-) bin/setup
-) browser http://localhost:3000/
-) Create your first admin user
-) login page: demo, demo123
-) redirect again on root: http://localhost:3000/
-) then every time you click: Create your first admin user
-) redirect again on root: http://localhost:3000/   (without show login or signup page)

In every redirection to the root there is a message in the log:

> ...app/controllers/alchemy/base_controller.rb:52
> /!\ Failed to permit index on :alchemy_admin_dashboard for:
> #<Alchemy::User id: 1, firstname: nil, lastname: nil, login: "demo", email: "demo@example.com", gender: nil, language: nil, last_request_at: "2018-09-24 19:33:49", created_at: "2018-09-24 18:43:45", updated_at: "2018-09-24 19:17:06", creator_id: nil, updater_id: nil, cached_tag_list: nil, alchemy_roles: "member", tag_names: []>
> 
> Redirected to http://localhost:3000/
>

**Comment by agorneo** [comment]
The same happens also in the deployed demo (from button in alchemy_cms readme)

https://itg-alchemy-demo.herokuapp.com/

**Comment by tvdeyen** [comment]
@agorneo the problem you are describing is not related to this 4 year old issue. The issue itself has been resolved. Please open a new issue at the AlchemyCMS repository as the described issue is not related to this demo application. Thanks
