### ISSUE TITLE
Cannot login with `demo` or `admin`

### ISSUE THREAD

**Issue by delphaber** [AlchemyCMS/alchemy-demo#11]
Hi :)

I cannot login using neither `demo` `demo123` nor `admin` `secret123`. It redirects me always to the login page. I tried your heroku hosted app, I tried a fresh new heroku app I deployed with the 'Deploy to Heroku' button and I tried on my mac.

I tried to understand why, but I was not able to :(

I noticed that `authenticate_user!` in alchemy-devise/sessions_controllers does not redirect the user, so username and password are valid, but `current_user` method always returns `nil`. I don't know if this helps you :)

**Comment by delphaber** [comment]
I tried also to `bundle update` eveything, but achemy_cms 4.2.0.rc2 won't let log me in neither :(

**Comment by tvdeyen** [comment]
Thanks for reporting

Fixed by https://github.com/AlchemyCMS/alchemy-devise/pull/81
