### ISSUE TITLE
Application error when clicking on the link to the demo

### ISSUE THREAD

**Issue by cyrilcourvoisier** [AlchemyCMS/alchemy-demo#201]
After clicking on the provided link for the demo (https://alchemy-demo.herokuapp.com), I got this error:

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
> heroku logs --tail

Web browser: Safari 16.4

**Comment by tvdeyen** [comment]
Demo works again at https://demo.alchemy-cms.com
