### ISSUE TITLE
bin/rails setup : rails aborted! Don't know how to build task 'setup'

### ISSUE THREAD

**Issue by agorneo** [AlchemyCMS/alchemy-demo#4]
Hello,

After I clone the demo I run the "bin/rails setup" as the readme instructs but I get the message:

> rails aborted!
> Don't know how to build task 'setup'

I found out a setup file in the bin folder but it does not have a ".rake" ext and no tasks in it

Could you please advise me on this. I must be missing something...

Thank you in advance for your kind help and time

**Comment by tvdeyen** [comment]
The correct command is

```bash
bin/setup
```
