### ISSUE TITLE
Routing Error: Alchemy::Page not found "/"

### ISSUE THREAD

**Issue by agorneo** [AlchemyCMS/alchemy-demo#5]
Steps:
-) delete demo user
-) browser http://localhost:3000/
-) Create your first admin user
-) user admin details - save
-) This language tree does not exist - Create English as a new language tree
-) Here **I did not create the English language tree** and click leave - logout 
-) redirect to http://localhost:3000/
-) Routing Error: Alchemy::Page not found "/"
-) Then each time I get the same error

**Comment by tvdeyen** [comment]
Is the language root page you created public? If not, this is intentional. If you don’t have any public page, we render a 404 (or Page not found error in development mode)

**Comment by agorneo** [comment]
No I did not create the english language tree and logged out
So there are not any pages, so no root...
I see.. Logical :)
Thank you
