### ISSUE TITLE
Changes in page show in preview but not in the live page

### ISSUE THREAD

**Issue by agorneo** [AlchemyCMS/alchemy-demo#6]
In https://alchemy-demo.herokuapp.com/test-seite I have made one change in the heading of 2nd block and add all an image.

While I can see those changes in the preview admin page
https://alchemy-demo.herokuapp.com/admin/pages/69/edit
the live page shows the old version of the page without my changes

It looks like a problem with caching...

**Comment by tvdeyen** [comment]
Do you published the changes? If not, this is intentional. Unpublished changes are not visible on the life page until you publish them.

**Comment by agorneo** [comment]
You were correct... :)
I thought that "Publish Page" means like a flag, on or off, published or unpublished...
Thank you
The "unpublish" action is to uncheck the "Public" in Page Properties?

**Comment by tvdeyen** [comment]
Yes.
